# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: khlopko/setup-swift@8e40832f03d3d3d672037ad9d9bba479fcb284fb
      with:
        swift-version: "main-snapshot"
    - name: build
      run: swift build
    - name: run tests
      run: swift test
  build-ubuntu:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: khlopko/setup-swift@8e40832f03d3d3d672037ad9d9bba479fcb284fb
      with:
        swift-version: "main-snapshot"
    - name: build
      run: swift build
    - name: run tests
      run: swift test
  build-macos-stable:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: khlopko/setup-swift@8e40832f03d3d3d672037ad9d9bba479fcb284fb
      with:
        swift-version: "5.10"
    - name: build
      run: swift build
    - name: run tests
      run: swift test
  build-ubuntu-stable:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v4
    - uses: khlopko/setup-swift@8e40832f03d3d3d672037ad9d9bba479fcb284fb
      with:
        swift-version: "5.10"
    - name: build
      run: swift build
    - name: run tests
      run: swift test

