# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@5997f5179a4d8338f20f6cf094de5024731485ac
      with:
          swift-version: "main-snapshot"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: build
      run: swift build
    - name: run tests
      run: swift test

