name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  setup:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    - name: Cache Swift toolchain
      uses: actions/cache@v4
      with:
        path: ~/.swiftenv
        key: ${{ runner.os }}-swift-${{ hashFiles('**/Package.swift') }}
        restore-keys: |
          ${{ runner.os }}-swift-
    - name: Build
      run: swift build
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: .build/

  swift-tests:
    needs: setup
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .build/
    - name: Run Swift tests
      run: swift test
      continue-on-error: true

  spec-tests:
    needs: setup
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: swift-actions/setup-swift@v2
      with:
        swift-version: "6.0"
    - name: Download build artifacts
      uses: actions/download-artifact@v4
      with:
        name: build-artifacts
        path: .build/
    - name: Run spec tests
      working-directory: ./Tests
      run: python spec_tests.py
      continue-on-error: true
