# This workflow will build a Swift project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-swift

name: test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-macos:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    - uses: khlopko/setup-swift@66e094269fa2f161aa888ef47e9c631cd470a11f
      with:
        swift-version: "main-snapshot"
    - name: build
      run: swift build
    - name: run tests
      run: swift test

